Update blank.yml

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -6,9 +6,9 @@ name: CI
 # events but only for the main branch.
 on:
   push:
-    branches: [ main ]
+    branches: [ main]
   pull_request:
-    branches: [ main ]
+    branches: [ main]
 
 # A workflow run is made up of one or more jobs that can run sequentially or in parallel
 jobs:
@@ -23,17 +23,29 @@ jobs:
     # Steps represent a sequence of tasks that will be executed as part of the job
     steps:
     # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
-    - uses: actions/checkout@v3
+    - uses: actions/checkout@v2
+    -name: go to the correct folder
+    run: cd FRC-2023-CODE
 
-    # Declares the repository safe and not under dubious ownership.
-    - name: Add repository to git safe directories
-      run: git config --global --add safe.directory $GITHUB_WORKSPACE
-    - name: cd to the correct commands
-      run: cd FRC-2023-CODE
     # Grant execute permission for gradlew
     - name: Grant execute permission for gradlew
       run: chmod +x gradlew
-
+  
     # Runs a single command using the runners shell
     - name: Compile and run tests on robot code
       run: ./gradlew build
+
+    # Runs a single command using the runners shell
+    - name: Simulate robot code
+      run: |
+        set +e
+        (
+          timeout --preserve-status 10s ./gradlew simulateJava
+        )
+        if [ $? -eq 143 ]; then
+          echo 'Simulation SUCCESS!'
+          exit 0
+        else
+          echo 'Simulation FAILED!'
+          exit 1
+        fi
