Update gradle-publish.yml

diff --git a/.github/workflows/gradle-publish.yml b/.github/workflows/gradle-publish.yml
--- a/.github/workflows/gradle-publish.yml
+++ b/.github/workflows/gradle-publish.yml
@@ -36,3 +36,17 @@ jobs:
     # Runs a single command using the runners shell
     - name: Compile and run tests on robot code
       run: ./gradlew build
+        # Runs a single command using the runners shell
+    - name: Simulate robot code
+      run: |
+        set +e
+        (
+          timeout --preserve-status 10s ./gradlew simulateJava
+        )
+        if [ $? -eq 143 ]; then
+          echo 'Simulation SUCCESS!'
+          exit 0
+        else
+          echo 'Simulation FAILED!'
+          exit 1
+        fi
